let uid=localStorage.getItem("uid"),lat=null,lon=null;
async function status(){try{let d=await(await fetch("/api/status")).json();document.getElementById("status").textContent=d.online?"🟢 Local AI Online":"🔴 Start Ollama"}catch{document.getElementById("status").textContent="🔴 Backend Offline"}}
async function products(){let d=await(await fetch("/api/products")).json();document.getElementById("products").innerHTML=d.map(p=>`<div class="product"><div class="icon">${p.icon}</div><div class="cat">${p.category}</div><h3>${p.name}</h3><div class="price">${p.price}</div></div>`).join("")}
async function save(){let name=document.getElementById("name").value.trim();if(!name)return alert("Name enter karo.");let r=await fetch("/api/user",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,phone:document.getElementById("phone").value,assistance_type:document.getElementById("type").value})});let d=await r.json();uid=d.user_id;localStorage.setItem("uid",uid);alert("Profile saved")}
async function send(text=null){let m=(text??document.getElementById("msg").value).trim();if(!m)return;if(!uid)return alert("Pehle profile save karo.");add(m,"user");document.getElementById("msg").value="";try{let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:+uid,message:m})});let d=await r.json();if(!r.ok)throw Error(d.detail);add(d.answer,"bot");speak(d.answer)}catch(e){add("❌ "+e.message,"bot")}}
function add(t,c){let x=document.createElement("div");x.className=c;x.textContent=t;document.getElementById("chat").appendChild(x);document.getElementById("chat").scrollTop=99999}
function voice(){let S=window.SpeechRecognition||window.webkitSpeechRecognition;if(!S)return alert("Chrome/Edge use karo.");let r=new S();r.lang="hi-IN";r.onresult=e=>send(e.results[0][0].transcript);r.start()}
function speak(t){if(!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="hi-IN";u.rate=.9;speechSynthesis.speak(u)}
function loc(){navigator.geolocation.getCurrentPosition(p=>{lat=p.coords.latitude;lon=p.coords.longitude;document.getElementById("location").innerHTML=`${lat.toFixed(6)}, ${lon.toFixed(6)}<br><a target="_blank" href="https://www.google.com/maps?q=${lat},${lon}">Open Maps</a>`},e=>alert(e.message))}
function hospitals(){if(lat===null){loc();setTimeout(hospitals,1800);return}window.open(`https://www.google.com/maps/search/hospitals/@${lat},${lon},14z`,"_blank")}
status();products();
function previewImage(e){const f=e.target.files[0],img=document.getElementById("preview");if(!f)return;img.src=URL.createObjectURL(f);img.style.display="block";}
async function analyzeVision(){const f=document.getElementById("imageInput").files[0],box=document.getElementById("visionAnswer");if(!f)return alert("Pehle photo choose karo.");box.textContent="👁️ Vision AI image analyze kar raha hai...";const form=new FormData();form.append("image",f);form.append("question",document.getElementById("visionQuestion").value||"Describe this image in simple language and tell me anything useful for accessibility.");try{const r=await fetch("/api/vision",{method:"POST",body:form}),d=await r.json();if(!r.ok)throw Error(d.detail);box.textContent=d.answer;speak(d.answer)}catch(e){box.textContent="❌ "+e.message}}
function clearVision(){document.getElementById("imageInput").value="";document.getElementById("preview").style.display="none";document.getElementById("visionQuestion").value="";document.getElementById("visionAnswer").textContent="Vision answer will appear here.";}
